---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "gke-preemptible-sniper.fullname" . }}
rules:
        - apiGroups:
                - ""
                resources:
                - nodes
                verbs:
                - get
                - list
                - watch
        - apiGroups:
                - ""
                resources:
                - nodes/status
                verbs:
                - patch
