---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gke-preemptible-sniper.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gke-preemptible-sniper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gke-preemptible-sniper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
