name: CI

on:
  push:
    branches:
      - "feature/*"
      - "dependabot/*"
  workflow_call:
    outputs:
      overall-result:
        description: "Overall test result"
        value: ${{ jobs.report.outputs.overall-result }}

jobs:
  unittest:
    uses: ./.github/workflows/unittest.yml
    secrets: inherit

  report:
    needs: [unittest]
    runs-on: ubuntu-latest
    outputs:
      overall-result: ${{ steps.check.outputs.result }}
    steps:
      - name: Set overall result
        id: check
        run: |
          if [[ "${{ needs.unittest.outputs.test-result }}" == "success" ]]; then
            echo "result==success" >> $GITHUB_OUTPUT
          else
            echo "result==failure" >> $GITHUB_OUTPUT
          fi
